package com.crystelle.electrolife.model;

import androidx.annotation.NonNull;

/**
 * REVISED: Model representing a dynamic insight generated by the recommendation engine.
 * Task 1: Enforces immutability for core identity fields using the 'final' keyword.
 * Task 2: Implements Constructor Chaining to resolve "never used" static analysis warnings.
 * This pattern ensures that all instances share the same icon-determination logic.
 */
public class SmartRecommendation {

    // Core identity fields are final to ensure immutability once an insight is generated
    private final String title;
    private final String description;
    private final String type; // info, warning, danger
    private final String iconName;

    // These fields remain non-final to allow for post-calculation enrichment if needed
    private String potentialSavings;
    private String actionable;

    /**
     * REVISION: Base Constructor for general system insights.
     * This is now "used" by the overloaded constructor via chaining.
     *
     * @param title       The headline of the recommendation.
     * @param description The detailed text for the user.
     * @param type        The severity level (danger, warning, info).
     */
    public SmartRecommendation(String title, String description, String type) {
        this.title = title;
        this.description = description;
        this.type = type;
        this.iconName = determineIcon(type);

        // Initialize with safe defaults to prevent NullPointerExceptions in the UI
        this.potentialSavings = "Calculating...";
        this.actionable = "No specific action required.";
    }

    /**
     * REVISION: Overloaded constructor for high-detail insights.
     * FIX: Calls 'this(...)' to chain to the base constructor, resolving the "unused" warning.
     *
     * @param title       The headline of the recommendation.
     * @param description The detailed text for the user.
     * @param type        The severity level.
     * @param savings     Specific calculated currency/energy savings.
     * @param action      A specific instruction for the user.
     */
    public SmartRecommendation(String title, String description, String type, String savings, String action) {
        // This call 'uses' the 3-parameter constructor as the starting point
        this(title, description, type);

        // Overwrite the defaults with specific calculation data
        this.potentialSavings = savings;
        this.actionable = action;
    }

    /**
     * Internal helper to resolve iconography based on recommendation severity.
     * @param type The alert category.
     * @return The resource name for the icon.
     */
    private String determineIcon(String type) {
        if (type == null) return "ic_settings";

        switch (type) {
            case "danger":
                return "ic_zap";
            case "warning":
                return "ic_lightbulb";
            default:
                return "ic_settings";
        }
    }

    // --- GETTERS (Used by RecommendationsAdapter for UI binding) ---

    @NonNull
    public String getTitle() {
        return title != null ? title : "Recommendation";
    }

    public String getDescription() {
        return description;
    }

    public String getType() {
        return type;
    }

    public String getIconName() {
        return iconName;
    }

    public String getPotentialSavings() {
        return potentialSavings;
    }

    public String getActionable() {
        return actionable;
    }

    // --- SETTERS ---

    public void setPotentialSavings(String potentialSavings) {
        this.potentialSavings = potentialSavings;
    }

    public void setActionable(String actionable) {
        this.actionable = actionable;
    }
}